steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'osm-borders', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--name', 'osm-borders', '--entrypoint', 'python', 'osm-borders', '/app/init_dictionaries.py']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['commit',
           '-c', "CMD /app/docker-entrypoint.sh",
           '-c', 'ENTRYPOINT "/app/docker-entrypoint.sh"',
           'osm-borders', 'osm-borders-step2'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'osm-borders-step2', '${_IMAGE_NAME}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'osm-borders',
           '--image=${_IMAGE_NAME}',
           '--region=europe-north1',
           '--platform=managed',
           '--memory=512Mi',
           '--allow-unauthenticated',
           '--max-instances=2',
           '--set-env-vars=DISABLE_UPDATE=True'
    ]

images: ['${_IMAGE_NAME}']
substitutions:
    _IMAGE_NAME: 'gcr.io/osm-vink/osm-borders:latest'

timeout: 1800s
