#!/bin/sh

export LC_ALL="pl_PL.UTF-8"
export LANG="pl_PL.UTF-8"
export LC_COLLATE="pl_PL.UTF-8"
export LC_CTYPE="pl_PL.UTF-8"
export LC_MESSAGES=C
export LC_MONETARY="pl_PL.UTF-8"
export LC_NUMERIC="pl_PL.UTF-8"
export LC_TIME="pl_PL.UTF-8"
export PYTHONIOENCODING="utf-8"


chroot -u nobody / /home/w/venv/osm-borders/bin/python3.6 /home/w/osm/osm-borders/rest_server.py
