# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teryt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='teryt.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0bteryt.proto\"d\n\tTercEntry\x12\x0b\n\x03woj\x18\x01 \x01(\x05\x12\x0e\n\x06powiat\x18\x02 \x01(\x05\x12\x0b\n\x03gmi\x18\x03 \x01(\x05\x12\x0c\n\x04rodz\x18\x04 \x01(\x05\x12\x10\n\x08nazwadod\x18\x05 \x01(\t\x12\r\n\x05nazwa\x18\x06 \x01(\t\"Q\n\tSimcEntry\x12\x0c\n\x04terc\x18\x01 \x01(\x05\x12\n\n\x02rm\x18\x02 \x01(\x05\x12\r\n\x05nazwa\x18\x03 \x01(\t\x12\x0b\n\x03sym\x18\x04 \x01(\x05\x12\x0e\n\x06parent\x18\x05 \x01(\x05\"f\n\tUlicEntry\x12\x0b\n\x03sym\x18\x01 \x01(\x05\x12\r\n\x05symul\x18\x02 \x01(\x05\x12\r\n\x05\x63\x65\x63ha\x18\x03 \x01(\t\x12\x0f\n\x07nazwa_1\x18\x04 \x01(\t\x12\x0f\n\x07nazwa_2\x18\x05 \x01(\t\x12\x0c\n\x04terc\x18\x06 \x01(\x05\"Z\n\x0eUlicMultiEntry\x12\r\n\x05symul\x18\x01 \x01(\x05\x12\r\n\x05\x63\x65\x63ha\x18\x02 \x01(\t\x12\r\n\x05nazwa\x18\x03 \x01(\t\x12\x1b\n\x07\x65ntries\x18\x04 \x03(\x0b\x32\n.UlicEntryb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TERCENTRY = _descriptor.Descriptor(
  name='TercEntry',
  full_name='TercEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='woj', full_name='TercEntry.woj', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='powiat', full_name='TercEntry.powiat', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gmi', full_name='TercEntry.gmi', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rodz', full_name='TercEntry.rodz', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nazwadod', full_name='TercEntry.nazwadod', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nazwa', full_name='TercEntry.nazwa', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=115,
)


_SIMCENTRY = _descriptor.Descriptor(
  name='SimcEntry',
  full_name='SimcEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='terc', full_name='SimcEntry.terc', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rm', full_name='SimcEntry.rm', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nazwa', full_name='SimcEntry.nazwa', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sym', full_name='SimcEntry.sym', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent', full_name='SimcEntry.parent', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=198,
)


_ULICENTRY = _descriptor.Descriptor(
  name='UlicEntry',
  full_name='UlicEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sym', full_name='UlicEntry.sym', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symul', full_name='UlicEntry.symul', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cecha', full_name='UlicEntry.cecha', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nazwa_1', full_name='UlicEntry.nazwa_1', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nazwa_2', full_name='UlicEntry.nazwa_2', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='terc', full_name='UlicEntry.terc', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=302,
)


_ULICMULTIENTRY = _descriptor.Descriptor(
  name='UlicMultiEntry',
  full_name='UlicMultiEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symul', full_name='UlicMultiEntry.symul', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cecha', full_name='UlicMultiEntry.cecha', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nazwa', full_name='UlicMultiEntry.nazwa', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entries', full_name='UlicMultiEntry.entries', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=394,
)

_ULICMULTIENTRY.fields_by_name['entries'].message_type = _ULICENTRY
DESCRIPTOR.message_types_by_name['TercEntry'] = _TERCENTRY
DESCRIPTOR.message_types_by_name['SimcEntry'] = _SIMCENTRY
DESCRIPTOR.message_types_by_name['UlicEntry'] = _ULICENTRY
DESCRIPTOR.message_types_by_name['UlicMultiEntry'] = _ULICMULTIENTRY

TercEntry = _reflection.GeneratedProtocolMessageType('TercEntry', (_message.Message,), dict(
  DESCRIPTOR = _TERCENTRY,
  __module__ = 'teryt_pb2'
  # @@protoc_insertion_point(class_scope:TercEntry)
  ))
_sym_db.RegisterMessage(TercEntry)

SimcEntry = _reflection.GeneratedProtocolMessageType('SimcEntry', (_message.Message,), dict(
  DESCRIPTOR = _SIMCENTRY,
  __module__ = 'teryt_pb2'
  # @@protoc_insertion_point(class_scope:SimcEntry)
  ))
_sym_db.RegisterMessage(SimcEntry)

UlicEntry = _reflection.GeneratedProtocolMessageType('UlicEntry', (_message.Message,), dict(
  DESCRIPTOR = _ULICENTRY,
  __module__ = 'teryt_pb2'
  # @@protoc_insertion_point(class_scope:UlicEntry)
  ))
_sym_db.RegisterMessage(UlicEntry)

UlicMultiEntry = _reflection.GeneratedProtocolMessageType('UlicMultiEntry', (_message.Message,), dict(
  DESCRIPTOR = _ULICMULTIENTRY,
  __module__ = 'teryt_pb2'
  # @@protoc_insertion_point(class_scope:UlicMultiEntry)
  ))
_sym_db.RegisterMessage(UlicMultiEntry)


# @@protoc_insertion_point(module_scope)
